Nesecidad_nutricional  = 0.12
Tasa_crecimiento_pasto = 0.08
Incremento_por_lluvia  = 0.05
Perdida_por_sequia     = 0.10
Perdida_por_floracion  = 0.12
Dias                   = 365
Cantidad_de_Potreros   = 200
Area_potreros_min      = 500
Area_potreros_max      = 1000
Max_x                  = 1000
Max_y                  = 1000
Min_x                  = 100
Min_y                  = 100
Cantidad_lotes         = 5
Cantidad_min_animales  = 8
Cantidad_max_animales  = 10
Aforo_min              = 1000 
Aforo_max              = 1200
Ocupacion              = 3
Descanso               = 30
v                      = 3 # cantidad m?xima de d?as ocupadosa de manera consecutiva 
forraje_un_dia         = 12 # forraje (en kg) que crece en un d?a despu?s de llegar a cero
dias_desocupado_forraje = 31 